config/routes.rb
Rails.application.routes.draw do
  
  #サインアップとサインインのルーティングを作っている users/sign_up など自動でURLが設定される
  #usersフォルダ配下のコントローラーを使用するように指定してルーティングを変える 対応するコントローラーを変えている
  # Prefix→OO系は: "OOディレクトリの/OOコントローラーを対応させる  という意味
  #
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }
  #users/registrations系にshow画面へのrouteingを追加
  #userモデル用のコントローラーのshowアクションを割り当てるために必要な処理
  devise_scope :user do
    get "/users/show", to: "users/registrations#show"
  end

  
  
  
  #topコントローラーのインデックスアクションアクションを指定
  #rootにする場合はurlではなくアクション指定なので # を使う
  root 'top#index'
  
  #検索用のURLとアクションを設定 「verb 'prefix', to: 'コントローラー名#アクション名'」
  post 'search', to: 'card#search'

  #resoucesを使う場合は以下のように書ける resouces コントローラー名
  resources :list, only: %i(new create edit update destroy) do
    #親子関係にある場合は入れ子構造にできる
    #Cardモデルに対しても同様の処理を可能にする
    resources :card, except: %i(index)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    #現在のユーザーで作成したlistを全て取得してインスタンス変数に代入する
    @lists = List.where(user: current_user).order("created_at ASC")
    @search_result_cards = []
    #@search_result_cards =  Card.where(user: current_user).order("created_at ASC")
  end
  
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<div class="search-form-area">
  <div class="search-form text-center">
    <%= form_with url: search_path, method: :post, local: true do |f| %>
      <%= f.text_field :keyword, value: @keyword, :placeholder => "カード名を入力" %>
      <%= f.submit "検索", {class: "search-button"} %>
    <% end %>
  </div>
</div>

<div class="topPage">
  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか？" } %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list)) %>
          </div>
        </div>

        <div class="cardWrapper">
          <% list.cards.each do |card| %>
            <!--link_toをブロックで使用する場合は書き方が異なるので注意  pathの引数は2つ指定することも可能-->
            <%= link_to list_card_path(list, card), class:"cardDetail_link" do %>
              <div class="card">
                <h5 class="card_title"><%= card.title %></h5>
                <% if card.memo.size > 0 %>
                  <div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
                <% end %>
              </div>
            <% end %>
          <% end %>

          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "カードを追加", new_list_card_path(list), class: "addCard_link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!--検索結果を表示してみる-->
  <% @search_result_cards.each do |search_result_card| %>
    <p><%= search_result_card.title %></p>
  <% end %>

</div>