config/routes.rb
Rails.application.routes.draw do
  
  #サインアップとサインインのルーティングを作っている users/sign_up など自動でURLが設定される
  #usersフォルダ配下のコントローラーを使用するように指定してルーティングを変える 対応するコントローラーを変えている
  # Prefix→OO系は: "OOディレクトリの/OOコントローラーを対応させる  という意味
  #
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }
  #users/registrations系にshow画面へのrouteingを追加
  #userモデル用のコントローラーのshowアクションを割り当てるために必要な処理
  devise_scope :user do
    get "/users/show", to: "users/registrations#show"
  end

  
  
  
  #topコントローラーのインデックスアクションアクションを指定
  #rootにする場合はurlではなくアクション指定なので # を使う
  root 'top#index'
  
  #検索用のURLとアクションを設定 「verb 'prefix', to: 'コントローラー名#アクション名'」
  post 'search', to: 'card#search'

  #resoucesを使う場合は以下のように書ける resouces コントローラー名
  resources :list, only: %i(new create edit update destroy) do
    #親子関係にある場合は入れ子構造にできる
    #Cardモデルに対しても同様の処理を可能にする
    resources :card, except: %i(index)
  end

end

app/models/card.rb
class Card < ApplicationRecord
    
  #listとの結びつきは 多対1なので belongs_to
  belongs_to :list

  #usetとの結びつきを用意
  belongs_to :user

  #バリデーションを記述する in→OO文字以上OO文字以下  maximum→OO文字まで
  validates :title, length: {in: 1..50}
  validates :memo, length: {maximum: 400}

end

app/controllers/card_controller.rb
class CardController < ApplicationController
  
  #同じものはまとめる
  before_action :set_card, only: %i(show edit update destroy)

  def new
    #フォーム用に空のインスタンスを用意
    @card = Card.new
    #listとのアソシエーションがあるため、listのインスタンスも必要 id指定で対象のデータを取得 list_id自体はURLのid番号を参考にする find_by(idは→params[リストのid]の値を代入)
    @list = List.find_by(id: params[:list_id])
  end

  def create
    #フォームに入力された値をインスタンス変数へ代入 入力値はHTTPリクエストのハッシュで取得
    @card = Card.new(card_params)
    #保存が上手くいったらrootへ
    if @card.save
      redirect_to :root
    else
      #HTTPリクエスト必要ないのでrender: :アクション名
      render action: :new
    end
  end

  def show
    #set_cardメソッドで@cardインスタンス変数を取得
  end

  def edit
    #set_cardメソッドで@cardインスタンス変数を取得
    #ログインユーザーが作成したリストを全部取得してインスタンス変数へ
    @lists = List.where(user: current_user)
  end

  def update
    #set_cardメソッドで@cardインスタンス変数を取得
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      #HTTPリクエスト必要ないのでrender: :アクション名
      render action: :edit
    end
  end

  def destroy
    #show画面の@cardインスタンスを消し去るだけ
    @card.destroy
    redirect_to :root
  end

  #検索用のメソッド
  def search
    #入力されたキーワードを変数へ
    keyword = params[:keyword]
    #user_idと検索キーワードを元にDBから値を取得
    @search_result_cards = Card.where('user_id = ? and title like?', current_user.id, "%#{keyword}%")
    #現在の出力形式上、Listをもう一度取得する必要あり
    @lists = List.where(user: current_user).order("created_at ASC")
    #検索結果をindex.htmlに表示する
    render "top/index"
  end


  private 
  #データベースへの値の入力を許可するメソッド 基本的に1つのコントローラーに1つは必ず書くことになるはず
  def card_params
    #permitで3つのカラムを全て変更できるように設定
    params.require(:card).permit(:title, :memo, :list_id, :user_id)
  end

  def set_card
    @card = Card.find_by(id: params[:id])
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/edit.html.erb
<div class="cardeditPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div>
      <!--リスト編集欄 selectで選択式にする-->
      <div class="cardeditForm_memo">
        <label>リスト名</label>
        <%= select :card, :list_id, @lists.map{ |list| [list.title, list.id] }, {}, { class: 'form-control' } %>
      </div>
      <div class="text-center"><%= f.submit "更新する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/card/new.html.erb
<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <%= f.hidden_field :user_id, value: @list.user_id %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardnewForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
      <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/card/show.html.erb
<div class='carddetailPage'>
  <div class="container">
    <div class="cardContents">
      <div class="cardContents_title">
        <div>タイトル</div>
        <h2><%= @card.title %></h2>
      </div>
      <div class="cardContents_memo">
        <div>メモ</div>
        <div><%= @card.memo %></div>
      </div>
      <div class="cardContents_listStatus">
        <div>リスト名</div>
        <!--アソシエーションのあるモデルの情報は 「インスタンス変数.モデル名」 で相互に取得可能 -->
        <div><%= @card.list.title %></div>
      </div>
      
      <!--編集画面への移動ボタンを追加-->
      <div class="cardContents_btnArea">
        <!--パスには2つの引数を渡す カードの更新にはリスト情報と カード情報の2つが必要-->
        <%= link_to '編集する', edit_list_card_path(@card.list, @card), class: "edit_btn" %>
        <%= link_to '削除する', list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete , data: { confirm: "このカードを削除して大丈夫ですか?" }  %>
      </div>
    </div>
  </div>
</div>